In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import os
import sklearn
from sklearn.preprocessing import StandardScaler

In [6]:
path = r"C:\Users\suhas\Documents\careerfoundry\ml\datasets\weather-processed.csv"

In [7]:
df = pd.read_csv(path)

In [8]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [9]:
# exclude DATE and MONTH columns
exclude_columns = ['DATE', 'MONTH']
columns_to_scale = [col for col in df.columns if col not in exclude_columns]

# Apply StandardScaler only to selected columns
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[columns_to_scale])

# Create a DataFrame from the scaled data
scaled_df = pd.DataFrame(scaled_data, columns=columns_to_scale)

final_df = pd.concat([df[exclude_columns].reset_index(drop=True), scaled_df], axis=1)

# Step 6: Export to CSV
final_df.to_csv(r'C:\Users\suhas\Documents\careerfoundry\ml\datasets\weather-scaled.csv', index=False)